name: Tests

on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - php: '8.0'
            dependencies: '--prefer-lowest'
          - php: '8.3'
            dependencies: ''

    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none

      - run: composer update --prefer-dist --no-interaction ${{ matrix.dependencies }}
      - run: composer test
